# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    beps_election_bundle.image_type:
        class: BepsElectionBundle\Form\Extension\ImageTypeExtension
        tags:
            - {name: form.type_extension, alias: file }       
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
